### ISSUE TITLE
Coordinator 프로토콜 정의, AppCoordinator 생성

### ISSUE THREAD

**Issue by junu0516** [GunZaStation/Rabit#1]
- [x] Coordinator 프로토콜 정의
- [x] AppCoordinator 생성
- [x] SceneDelegate에 TabBarController rootView로 적용
    - [x] 스토리보드 제거
    - [x] MainCoordinator.start() 메소드 구현
    - [x] 시뮬레이터에 TabBarController 띄워보기

**Comment by Hansolkkim** [comment]
제드 `ChildType` 열거형의 rawValue 타입을 Int로 지정해주지 않아도 될 것 같아요.
프로토타입에서는 제가 열거형 rawValue를 TabBarItem tag로 쓰려고 지정해줬었는데, 이번에는 `ChildType`가 tabBarItem 프로퍼티를 가지고 있으니까 따로 rawValue 타입을 지정해주지 않아도 될 것 같습니다.

**Comment by junu0516** [comment]
@Hansolkkim 
그러네요 ㅋㅋ 금요일에 같이 수정하죠!

**Comment by Hansolkkim** [comment]
@junu0516 제가 브랜치 안파고 작업해서 revert 한번 한거 떄문에 사진이랑 색상이 추가 됐다가 날라가버린거 같네요..ㅠㅠ

**Comment by junu0516** [comment]
@Hansolkkim  아 안그래도 확인했어요 ㅋㅋ 이전 커밋내역에 다행히 남아있긴 하더라구요 우선 그거 가져다 쓰고 금요일에 혹시 새로 asset 올리시면 그걸로 덮어쓰려 했습니당
