### ISSUE TITLE
GoalAddView 모달 UI 개선 및 완성, GoalDetail 속성 재정의

### ISSUE THREAD

**Issue by junu0516** [GunZaStation/Rabit#31]
- [x] GoalAddViewController의 InsertField 컴포넌트 배치 수정
- [x] 바텀 시트(Bottom Sheet) 구현 및 애니메이션 적용 확인
- [x] 날짜 확인, 시간 선택을 위한 화면 구현 및 선택한 정보 GoalAddViewModel로 전달

**Comment by junu0516** [comment]
<img src="https://user-images.githubusercontent.com/68586291/185798511-e2a85158-542c-4f82-8383-dec98693131f.png" width="30%;"/>

@Hansolkkim 
위와 같은 식으로 UI를 재구성해보려 하는데 어떠신가요!?

참고한 앱은 DayStamp 라는 앱입니다.

**Comment by Hansolkkim** [comment]
@junu0516 
오 좋습니다! 이쁘게 나오겠네요!
그럼 저도 ColorPickerView를 구현해보는 쪽으로 해봐야겠어요!
