### ISSUE TITLE
Realm 시험삼아 적용해보기

### ISSUE THREAD

**Issue by junu0516** [GunZaStation/Rabit#36]
- [x] Realm에 접근하는 Persistence Layer 싱글톤으로 우선 구현
- [x] 데이터 추가하고 읽어오는 것 확인
- [x] Realm에서 사용할 Entity 타입과 Model 간 전환을 위한 프로토콜 선언

**Comment by junu0516** [comment]
- 지금 사용하는 Model은 사실상 RxDataSources의 SectionModel 타입을 채택한 구조임
- Realm을 사용해서 Object를 상속받는 클래스를 정의하면 기존에 사용하던 Model을 구조체에서 클래스로 변경해야 할 뿐만 아니라, 기타 다른 설정을 해야되서 복잡해짐
- 따라서 Realm을 바라보는 클래스를 Entity로 선언하고, Repository 계층에서 이를 구조체인 Model 타입으로 변환해서 ViewModel로 넘기는게 좋을 것 같음
    - 하나의 타입이 여러 모듈에 의존하게 되면 그만큼 구조를 복잡하게 생각해야 하기 때문!

**Comment by junu0516** [comment]
@Hansolkkim 
카테고리 추가를 해보는 도중에 한 가지 고민이 생겼어요!

Realm에 객체를 추가할 때, 중복되는 데이터가 있으면 런타임오류가 발생하기 때문에 카테고리 추가 로직을
`입력값 전달 -> 중복 여부 검사 -> 중복이 없을 경우 Realm에 쓰기(write)` 과 같이 해야 할 것 같습니다.

여기서 중복 여부를 검사할 때, 예제 코드들을 좀 보니까 우선 Realm에서 모든 데이터를 Results 타입으로 가져오고 난 후에
여기서 `filter` 메소드 호출로 중복되는 데이터가 있는 지 검사하는 것 같더라구요.

지금은 데이터가 적어서 별 문제가 없지만 모든 상황에서 단순히 입력값 하나를 포함하고 있는 지를 검사하려고 매번 모든 데이터를 Realm에서 다 읽어들이는게 비효율적이라는.. 생각이 듭니다!

필터링 용도로 Realm과 Repository 간에 캐시(?) 같은 용도로 데이터를 들고 있어야 하는 별도의 무언가를 가지고 있어야 하는 지에 대해 어떻게 생각하시나요!!? 시간되실 때 요것도 얘기나눠봐요 ㅋ.ㅋ

----
ㅋㅋㅋ 같이 얘기하면서 바로 찾아본대로 primary key로 하나만 찾을 수 있긴 하네요 
우선 하나 정도 찾아오는건 괜찮지 않을까 싶어서 이걸로 해보겠습니다.

**Comment by Hansolkkim** [comment]
@junu0516 

Goal, GoalDetail 모델 타입 관련해서 보다가 제안하고 싶은게 생겼습니다!
지금 현재 Goal이라는 타입은 category 라는  String타입 프로퍼티와 [GoalDetal] 타입 프로퍼티를 가지고 있도록 되어있는데,
명칭 상으로보면 Goal 보다는 Category라는 이름이 더 어울리지 않을까 생각이 됐습니다.
그래서 Goal -> Category, GoalDetail -> Goal 로 이름 변경이 어떨지 한 번 여쭙고 싶습니다!

```swift
struct Category {
    let title: String
    let items: [Goal]
}

struct Goal {...}
```

이런 식으로 하면 괜찮지 않을까 싶습니다!

**Comment by Hansolkkim** [comment]
@junu0516 

아까 회의때 말씀드렸던, Realm의 반환 타입인 Results를 좀 더 간편하게 사용하기 위해서 Results 타입을 Array로 변환하는 extension을 하나 추가해볼까하는데, 제드 의견이 궁금합니다!

```swift
extension Results {
    func toArray<T>(ofType: T.Type) -> [T] {
        var array = [T]()

        for i in 0..<count {
            if let result = self[i] as? T {
                array.append(result)
            }
        }

        return array
    }
}
```
이렇게 메소드를 하나 추가해서 아래처럼 사용해보려고 합니다!
```swift
let filteredPhotoData = fetchedPhotoData.filter("categoryTitle == '\(운동)'").toArray(ofType: PhotoEntity.self)
```

**Comment by junu0516** [comment]
> @junu0516
> 
> Goal, GoalDetail 모델 타입 관련해서 보다가 제안하고 싶은게 생겼습니다! 지금 현재 Goal이라는 타입은 category 라는 String타입 프로퍼티와 [GoalDetal] 타입 프로퍼티를 가지고 있도록 되어있는데, 명칭 상으로보면 Goal 보다는 Category라는 이름이 더 어울리지 않을까 생각이 됐습니다. 그래서 Goal -> Category, GoalDetail -> Goal 로 이름 변경이 어떨지 한 번 여쭙고 싶습니다!
> 
> ```swift
> struct Category {
>     let title: String
>     let items: [Goal]
> }
> 
> struct Goal {...}
> ```
> 
> 이런 식으로 하면 괜찮지 않을까 싶습니다!

@Hansolkkim 
듣고 보니 솔이 말씀하신 대로 하는게 더 직관적일 것 같아요!
내일 만났을 때 바로 같이 수정하죠 ㅎㅎ

**Comment by junu0516** [comment]
> @junu0516
> 
> 아까 회의때 말씀드렸던, Realm의 반환 타입인 Results를 좀 더 간편하게 사용하기 위해서 Results 타입을 Array로 변환하는 extension을 하나 추가해볼까하는데, 제드 의견이 궁금합니다!
> 
> ```swift
> extension Results {
>     func toArray<T>(ofType: T.Type) -> [T] {
>         var array = [T]()
> 
>         for i in 0..<count {
>             if let result = self[i] as? T {
>                 array.append(result)
>             }
>         }
> 
>         return array
>     }
> }
> ```
> 
> 이렇게 메소드를 하나 추가해서 아래처럼 사용해보려고 합니다!
> 
> ```swift
> let filteredPhotoData = fetchedPhotoData.filter("categoryTitle == '\(운동)'").toArray(ofType: PhotoEntity.self)
> ```

@Hansolkkim 
이것도 대찬성입니다 ㅋㅋ
비슷한 맥락으로 저희 Repository는 Realm 외에도 (만일 추후에 Firebase를 사용한다면) 서버에서도 데이터를 얻어올 수 있는데,
수요일에 임시로 만들었던 Repository의 fetch() 메소드 같은 경우에 리턴값이 `Results` 와 같이 Realm에 의존적인 타입으로 명시되면, 결과적으로 Repository <-> Relam 간 결합이 높아지기 때문에 좋지 않을 것 같다고 생각했어요

제안해주신대로 Results -> Array 로 변환하는 메소드가 있으면 Realm에서 Repository로 미리 배열로 변환된 타입을 넘겨주기 때문에 Repository는 더 이상 Realm에서 명시한 타입을 바라볼 필요가 없어서 더 좋을 것 같아욧 :-)
