### ISSUE TITLE
캐릭터 디자인 제안

### ISSUE THREAD

**Issue by junu0516** [GunZaStation/Rabit#37]
@Hansolkkim 
지인 통해서 토끼 캐릭터를 몇개 얻었어요!
혹시 나중에 앱 아이콘이나, 다른 앱 화면에 이거 적용하는거 어떠십니까 ㅎㅎ

![image](https://user-images.githubusercontent.com/68586291/187041596-9e1cd4af-68c6-49dc-8c22-e5f1e69eed54.png)
![image](https://user-images.githubusercontent.com/68586291/187041618-24785135-0c80-4a47-af32-16c3366ec900.png)

**Comment by Hansolkkim** [comment]
너무 좋습니다ㅋㅋㅋ감사합니다!!
