### ISSUE TITLE
CalendarView(달력 화면) 구현하기

### ISSUE THREAD

**Issue by Hansolkkim** [GunZaStation/Rabit#47]
- [x] CalendarView에서 Calendar를 CollectionView로 보여주도록 구현
    - CalendarCell, CalendarHeaderView 구현
- [x] "Date -> 원하는 모습의 String" 변환에 사용할 DateConverter 구현
- [x] CalendarCollectionView 터치 기능 구현
    - CalendarCollectionView의 Cell이 최대 2개까지만 선택되도록 하는 기능 추가
- [x] PeriodSelectVC의 저장 버튼 활성화 기능 구현
- [x] PeriodSelectView가 처음 화면에 나올때 이미 선택되어 있는 Period에 해당하는 Cell이 selected 상태로 표현되도록 하기
- [x] 달력의 "달" 변경하는 방법 변경하기
  - 기존의 방법(swipe down)대로 하면 해당 이벤트가 BottomSheet 제거 이벤트와 겹침..

**Comment by Hansolkkim** [comment]
#### CalendarCollectionView에서 `periodStream`에 해당하는 날짜의 Cell이 Selected 되어있도록 초기 상태 구현하는 것에 있어서 고민 사항
- 기존에 사용했던 방법
    - stream에서 넘어온 값과 같은 값을 dataArray에서 찾아 index를 반환 -> 해당 index의 Cell을 selected 상태로 변경
- 이번 periodStream에 선택되어있는 **두 날짜**를 표시해야하기 때문에, 기존에 사용했던 방법을 사용하면 코드가 너무 길어지는 문제가 발생.
```swift
let selectedCellIndexStartDateSection = periodStream
    .withLatestFrom(dayData) { ($0, $1) }
    .compactMap { period, dayData in
        dayData.firstIndex { Date.isSameMonth(lhs: $0.firstDate, rhs: period.start) }
    }

let selectedCellIndexEndDateSection = periodStream
    .withLatestFrom(dayData) { ($0, $1) }
    .compactMap { period, dayData in
        dayData.firstIndex { Date.isSameMonth(lhs: $0.firstDate, rhs: period.end) }
    }

let selectedCellIndexStartDateItem = selectedCellIndexStartDateSection
    .withLatestFrom(dayData) { $1[$0].items }
    .withLatestFrom(periodStream) { ($0, $1) }
    .compactMap { data, period in
        data.firstIndex { Date.isSameDate(lhs: $0.date, rhs: period.start) }
    }

let selectedCellIndexEndDateItem = selectedCellIndexEndDateSection
    .withLatestFrom(dayData) { $1[$0].items }
    .withLatestFrom(periodStream) { ($0, $1) }
    .compactMap { data, period in
        data.firstIndex { Date.isSameDate(lhs: $0.date, rhs: period.end) }
    }

Observable.combineLatest(
    selectedCellIndexStartDateSection,
    selectedCellIndexStartDateItem
)
.withLatestFrom(dayData) { ($0.0, $0.1, $1) }
.map { sectionIndex, itemIndex, dayData in
    var dayData = dayData
    dayData[sectionIndex].items[itemIndex].isSelected = true
    return dayData
}
.bind(to: dayData)
.disposed(by: disposeBag)

Observable.combineLatest(
    selectedCellIndexEndDateSection,
    selectedCellIndexEndDateItem
)
.withLatestFrom(dayData) { ($0.0, $0.1, $1) }
.map { sectionIndex, itemIndex, dayData in
    var dayData = dayData
    dayData[sectionIndex].items[itemIndex].isSelected = true
    return dayData
}
.bind(to: dayData)
.disposed(by: disposeBag)
```

- Cell을 selected하는 로직에 대해서 더 고민이 필요할 것 같음.

**Comment by Hansolkkim** [comment]
#### DateComponent -> Date 변환에 관해

- 이전에 제드가 DateComponent 라는 커스텀 타입을 만들어서 Date 타입을 화면에 보여주기 쉽게, 그리고 전달받기도 편하도록 제작해주셨음.
- 그런데 이 타입을 이용해 나중에 알림과 같은 기능을 구현할 때에는 Swift가 해석가능한 **Date**타입으로 다시 형변환이 필요하지 않을까 생각했음.
    그래서 이전에 Airbnb 클론앱 제작 등을 진행할 때에는 Date 타입을 다른 커스텀 타입으로 변형하지 않고 그냥 그 타입 자체만 사용하면서 화면에 출력이 필요할 때에만 Converter를 이용해 현재 Calendar에 맞는 형태의 String을 반환하도록 했었음.

- 하지만 아래의 코드를 이용하면, 현재 커스텀 타입에 있는 year, month, day를 현재 사용자의 Calendar를 기준으로 한 연월일로 해석하여, Swift가 해석 가능한 (UTC 기준인) Date 타입으로의 변환이 가능.

```swift
struct DateComponent {
    let year, month, day: Int

    func toDateComponents() -> DateComponents {
        return DateComponents(
            year: year, 
            month: month, 
            day: day
        )
    }
}

let someDateComponent = DateComponent(year: 2022, month: 9, day: 8)

Calendar.current.date(from: someDateComponent.toDateComponents())
// 현재 캘린더를 기준으로 한 2022.09.07 날짜 데이터를 UTC를 기준으로 한 Date로 형변환
```

**Comment by junu0516** [comment]
> #### CalendarCollectionView에서 `periodStream`에 해당하는 날짜의 Cell이 Selected 되어있도록 초기 상태 구현하는 것에 있어서 고민 사항
> * 기존에 사용했던 방법
>   
>   * stream에서 넘어온 값과 같은 값을 dataArray에서 찾아 index를 반환 -> 해당 index의 Cell을 selected 상태로 변경
> * 이번 periodStream에 선택되어있는 **두 날짜**를 표시해야하기 때문에, 기존에 사용했던 방법을 사용하면 코드가 너무 길어지는 문제가 발생.
> 
> ```swift
> let selectedCellIndexStartDateSection = periodStream
>     .withLatestFrom(dayData) { ($0, $1) }
>     .compactMap { period, dayData in
>         dayData.firstIndex { Date.isSameMonth(lhs: $0.firstDate, rhs: period.start) }
>     }
> 
> let selectedCellIndexEndDateSection = periodStream
>     .withLatestFrom(dayData) { ($0, $1) }
>     .compactMap { period, dayData in
>         dayData.firstIndex { Date.isSameMonth(lhs: $0.firstDate, rhs: period.end) }
>     }
> 
> let selectedCellIndexStartDateItem = selectedCellIndexStartDateSection
>     .withLatestFrom(dayData) { $1[$0].items }
>     .withLatestFrom(periodStream) { ($0, $1) }
>     .compactMap { data, period in
>         data.firstIndex { Date.isSameDate(lhs: $0.date, rhs: period.start) }
>     }
> 
> let selectedCellIndexEndDateItem = selectedCellIndexEndDateSection
>     .withLatestFrom(dayData) { $1[$0].items }
>     .withLatestFrom(periodStream) { ($0, $1) }
>     .compactMap { data, period in
>         data.firstIndex { Date.isSameDate(lhs: $0.date, rhs: period.end) }
>     }
> 
> Observable.combineLatest(
>     selectedCellIndexStartDateSection,
>     selectedCellIndexStartDateItem
> )
> .withLatestFrom(dayData) { ($0.0, $0.1, $1) }
> .map { sectionIndex, itemIndex, dayData in
>     var dayData = dayData
>     dayData[sectionIndex].items[itemIndex].isSelected = true
>     return dayData
> }
> .bind(to: dayData)
> .disposed(by: disposeBag)
> 
> Observable.combineLatest(
>     selectedCellIndexEndDateSection,
>     selectedCellIndexEndDateItem
> )
> .withLatestFrom(dayData) { ($0.0, $0.1, $1) }
> .map { sectionIndex, itemIndex, dayData in
>     var dayData = dayData
>     dayData[sectionIndex].items[itemIndex].isSelected = true
>     return dayData
> }
> .bind(to: dayData)
> .disposed(by: disposeBag)
> ```
> 
> * Cell을 selected하는 로직에 대해서 더 고민이 필요할 것 같음.

저도 고민입니다 ......

**Comment by Hansolkkim** [comment]
[[제드의 48번 이슈]](https://github.com/GunZaStation/Rabit/commit/b9389b7840434d6d00f02784a2250ff7be67b6c4#r83549941)에서 말씀드렸던 방법을 실제로 적용시켜 Selected Cell 기능을 구현시켜보았습니다.

CalendarCollectionView의 Cell을 결정해주는 모델 타입 `Day`는 아래와 같이 정의했습니다.
```swift
struct Day {
    let date: Date // 실제 해당 모델이 가리키는 날짜
    let number: String // Label에 표시할 숫자
    var isSelected: Bool
    var isWithinDisplayedMonth: Bool
    var isBeforeToday: Bool
}
```
그리고 cell의 `configure(with:)` 메소드는 아래와 같이 정의했습니다.
```swift
final class CalendarCell: UICollectionViewCell {
    private let indicatingView: UIView = {...}() // cell이 선택됐음을 나타내줄 View

    private let dateLabel: UILabel = {...}() // 달력에서 날짜를 표시해주는 Label

    func configure(with day: Day) {
        if day.isBeforeToday {
            dateLabel.attributedText = day.number.strikeThrough()
        } else {
            dateLabel.text = day.number
        }

        updateSelectionStatus(of: day)
        isHidden = !day.isWithinDisplayedMonth
    }

    private func updateSelectionStatus(of day: Day) {
        if day.isSelected {
            applySelectedStyle()
        } else {
            applyDefaultStyle(isBeforeToday: day.isBeforeToday)
        }
    }

    private func applySelectedStyle() {
        dateLabel.textColor = .white
        indicatingView.isHidden = false
    }

    private func applyDefaultStyle(isBeforeToday: Bool) {
        dateLabel.textColor = isBeforeToday ? .systemGray4 : .label
        indicatingView.isHidden = true
    }
}
```
그리고 Jed가 사용했던 방법처럼, cell을 configure하려는 바인딩 로직 내에서 selected를 처리해보려고 했습니다.

```swift
final class PeriodSelecteViewController: UIViewController {
    private var countSelectedCell = 2
    ...
    private func bind() {
        ...
        viewModel.dayData
            .bind(to: calendarCollectionView.rx.items(dataSource: dataSource))
            .disposed(by: disposeBag)

        calendarCollectionView.rx.itemSelected
            .withUnretained(self)
            .bind(onNext: { viewController, _ in
                viewController.countSelectedCell += 1 // 터치되면 += 1
            })
            .disposed(by: disposeBag)

        calendarCollectionView.rx.itemSelected
            .withUnretained(self)
            .withLatestFrom(viewModel.dayData) {
                var dayData = $1

                if $0.0.countSelectedCell > 2 { // 3개째 터치되려고 하면
                    $0.0.countSelectedCell = 1 
                    dayData = dayData.map {
                        var temp = $0
                        temp.resetDaysSelectedState()  // 마지막에 터치된 애 말고는 isSelected 속성 값 모두 초기화
                        return temp
                    }
                }

                dayData[$0.1.section].items[$0.1.item].isSelected = true // 마지막에 터치된 애는 isSelected = true

                return dayData
            }
            .bind(to: viewModel.dayData)
            .disposed(by: disposeBag)

        calendarCollectionView.rx.modelSelected(Day.self)
            .filter { $0.isSelected == true }
            .bind(to: viewModel.selectedDay)
            .disposed(by: disposeBag)
    }

**Comment by Hansolkkim** [comment]
그런데 여기서 생긴 좀 부족한 점은, 
제가 CalendarCollectionView에서 선택된 Cell이 2개가 되도록 하기 위해 PeriodSelectVC에서 선언한 `countSelectedCell` 속성을 이용했는데,
이 점 때문에 Primitive Type인 Int타입인 `countSelectedCell`의 값에 의해 결과를 좌지우지하는게 조금 보기가 안좋다는 점이었습니다,,
CollectionView의 Selected Cell의 개수를 제한하는 방법에 대해서 조금 더 고민이 필요할 것 같습니다.

**Comment by junu0516** [comment]
@Hansolkkim 
추석 잘 보내셨나요!! 명절에도 불태우셨군요 ㅋㅋ 지금 확인했습니다 ㅎㅎ
모델에 선택 여부를 확인하기 위한 isSelected 속성을 추가하라는 말씀이셨군요!! 코멘트 보고 이해했어요
저같은 경우에는 터치할 수 있는 셀의 개수를 제한하지 않기 때문에 제안해주신 방식으로 그대로 적용할 수 있을 것 같아요!

추가로 피드백 주신거 보고 좀 더 제가 작성했던 코드에 대해서 생각해봤는데,
기존에는 셀을 터치하면 뷰-뷰모델 간 데이터 전달 및 업데이트 방식이 
    `셀 터치 -> 바로 뷰 업데이트 및 뷰모델에 변경된 터치정보 전달` 과 같은 흐름이었고, 이게 입출력 흐름을 분리해야 하는 원칙에 위배된 것이더라구요!!

MVVM 구조에서 입력 이벤트가 발생하면 바로 뷰를 업데이트 하지 않고 이를 바로 뷰모델로 전달하고 뷰모델이 모델의 값을 변경하면, 뷰는 변경된 모델 값에 맞춰 바로 뷰를 업데이트 하는 식으로 입출력의 흐름을 변경하는 식이어야 하는데,
이런 관점에서 보면 솔이 제안해주신 모델에 값을 추가하고, 모델의 값 변경에 따라 뷰가 업데이트 되는 방식으로 변경하는게 구조상 맞는 것 같습니다 ㅎㅎㅎ

남은 연휴동안 제안해주신 방식대로 리팩토링을 진행해야겠군요!

**Comment by Hansolkkim** [comment]
아 입출력 흐름 분리에 대해서도 생각해볼 수 있겠네요..ㅋㅋㅋ
원래 UI들이 동작하는 방식으로 본다면,
`View 조작 -> View 변경(출력) + ViewModel의 속성 변경(압력)`
위와 같은 흐름일텐데, Rx의 특성상 이런 흐름이 입출력 흐름 분리와 맞지 않다는 거네요. 
사실 저는 바꾼 방법이 어색하다고 느껴졌지만 그냥 넘겼는데..ㅋㅋㅋㅋ

이번에 수정한 Cell Select 흐름은
`View 조작 -> ViewModel의 속성 변경(입력)`
`ViewModel의 속성 변경으로 인한 View 변경(출력)`
이런 흐름이라, 입출력이 구분된다는 느낌이 있긴하네요!
좋은 코멘트 감사합니다ㅎㅎ
