### ISSUE TITLE
BottomSheet ContentsView 범위로 인한 이슈🚨

### ISSUE THREAD

**Issue by Hansolkkim** [GunZaStation/Rabit#62]
- 현재, BottomSheet의 TopBar에만 SwipeDown 효과를 한정시키기 위해 `hitTest(_:)`를 오버라이딩한 것 때문에 <u>BottomSheet 뷰 중에 ContentView 외의 부분을 터치하면 BottomSheet이 close 되는 이슈</u>를 발견했습니다.
- TimeSelectView의 Save 버튼의 Contraints를 일부(Top, CenterAlignment)만 설정해주다보니, 버튼의 일부가 BottomSheet.ContentView 바깥에 위치하게 되어 그 부분을 터치하면 위와 마찬가지로 BottomSheet이 close 되는 이슈가 있습니다.
![SS2022-10-01PM06 43 59](https://user-images.githubusercontent.com/92504186/193404051-a472c0a4-d8ad-4529-887e-82b504a94f2a.jpg)

**Comment by junu0516** [comment]
오.. 문제점 확인했습니다 치명적인 결함이네요 이거 ㅋㅋㅋ
노션에서 언급해주신대로 코드에 hitTest(:) 오버라이딩한 부분때문에 contentView 영역 바깥 부분이 터치되면, 터치가 dimmedView로 넘어가는게 맞는거 같아요!! 우선은 contentView 영역을 아얘 꽉 채우는식으로 레이아웃 수정해보겠습니다 ㅎ
감사합니다!!

**Comment by junu0516** [comment]
토요일밤에 한다는 작업을 뒤늦게 했습니다 ㅋㅋ,, 
아래와 같이 레이아웃을 바꾸면 현재 BottomSheet을 절반 이상 내렸을 때 `layoutSubViews()`가 무한으로 호출되는 문제가 발생하네요
```swift
contentView.snp.makeConstraints {
    $0.top.equalTo(topBarArea.snp.bottom)
//  $0.centerX.equalToSuperview()
//  $0.width.equalToSuperview().multipliedBy(0.9)
//  $0.height.equalToSuperview().multipliedBy(0.83)
    $0.leading.trailing.bottom.equalToSuperview()
}
```

이유는 현재 찾아보고 있고, 우선 떠오르는 대안은 아래 2가지 입니다.
- 위와 같이 contentView의 레이아웃을 BottomSheet내부에서 꽉 차도록 하고, layoutSubViews가 무한 호출되는 원인을 찾아 해결
- BottomSheet에서 contentView 외부 영역을 터치했을 때, 해당 터치를 다른 뷰에 굳이 넘길 필요가 없기 때문에 `hitTest`를 오버라이딩했던 부분을 제거

2안만 적용하면 바로 해결되긴 하지만, 사실상 contentView가 화면에 꽉 차는게 알맞기 때문에 레이아웃 관련해서 문제가 나타나는 부분 좀 더 고민해볼께요!
(이거 말고 다른 이슈 파서 한다던 작업도 같이 진행하고 있어요)
