### ISSUE TITLE
Rx 바인딩할 때, 클로저 내에서 간접적으로 self 순환참조하는 부분 수정

### ISSUE THREAD

**Issue by junu0516** [GunZaStation/Rabit#72]

**Comment by Hansolkkim** [comment]
![SS2022-10-12PM04 31 08](https://user-images.githubusercontent.com/92504186/195278743-fc228b74-a258-4022-aeee-4534fc43b544.jpg)

**Comment by junu0516** [comment]
감사합니다... 안알려주셨으면 누수난거 모르고 지나갔겠네요 😅

**Comment by Hansolkkim** [comment]
현재 StyleSelectViewController의 retain-cycle 문제는 완료했는데, PeriodSelectViewControlle에 RxDataSource로 인한 retain-cycle도 발견되어 해결 방안 모색중입니다.
