### ISSUE TITLE
UIButton.setBackgroundColor 메소드 개선

### ISSUE THREAD

**Issue by Hansolkkim** [GunZaStation/Rabit#97]
- 이전에 이미지 리사이징 개선 당시 찾아봤던 블로그에서 `UIGraphicsBeginImageContextWithOptions`를 사용해서 이미지를 렌더링하면 sRGB 색영역의 사용을 강제하기 때문에, 간단한 색칠을 위한 렌더링 때에는 iOS10부터 사용 가능하고, WWDC에서 사용을 권장했던 `UIGraphicsImageRenderer`를 사용하는 것이 좋다는 내용이 있었음.

**Comment by junu0516** [comment]
[sRGB](https://ko.wikipedia.org/wiki/SRGB) 는 또 뭘까요 ㅋㅋㅋㅋㅋ... 신기한 색상의 세계

**Comment by Hansolkkim** [comment]
좀 더 복잡한 색영역인 것 같아요ㅋㅋㅋ 사진 같은 애들은 좀 복잡한 색영역이 필요한데, 버튼은 단색이라 그런거 필요없는 느낌이더라구요!
