### ISSUE TITLE
Navigation 프로토콜의 프로퍼티 네이밍 정리

### ISSUE THREAD

**Issue by Hansolkkim** [GunZaStation/Rabit#98]
- 처음 Navigation 프로토콜을 사용한 이유는, **하위 모듈인 ViewModel이 상위 모듈인 Coordinator에게 지시**를 내리는 형태가 어색하다고 판단했기 때문임.
- 하지만 프로젝트를 진행하면서 네이밍에 신경을 쓰지 않고 있다보니, Navigation 프로토콜로 네비게이션 로직이 트리거 되도록 했지만 프로퍼티들의 네이밍이 마치 ViewModel이 Coordinator에게 지시를 내리는 듯한 네이밍이 되어버렸음.

**Comment by Hansolkkim** [comment]
@junu0516 
아래 사진처럼 바꿔볼까 하는데, 좀 어색하긴 하네요.. 제드 의견은 어떠신가요?
![SS2022-10-28PM04 46 34](https://user-images.githubusercontent.com/92504186/198533404-13430d4f-5ce2-49a9-9835-5f6ed606dbe6.jpg)

어색하다고 느낀 지점은, 어떤 프로퍼티는 여러 Navigation에서 공용으로 쓰기 위해 주체를 맨 앞에 넣지 못해서 `didRequest...` 이런 식으로 사용해야했고, 어떤 프로퍼티는 트리거 주체가 명확하게 `selectColorButtonDidTap` 이런 식으로 네이밍할 수 있었기 떄문이에요..ㅋㅋ

**Comment by Hansolkkim** [comment]
또 이렇게 해놓고 나니까, 나중에 해당 프로퍼티를 사용하는 코드에서는 `navigation.didSelectPhoto` 이런 식으로 사용할텐데, 좀 어색해지긴 하네요..
navigation의 네이밍이 잘못됐나.

**Comment by junu0516** [comment]
@Hansolkkim 
`didRequest...` 과 같은 식으로 **과거형(동사) + 행위내용 혹은 행위대상** 의 형식을 사용하는거면,
`selectColorButtonDidTap` 과 같이 색상 선택 버튼을 터치했다는 내용이 들어간 프로퍼티는 `tappedColorSelectButton` 혹은 `didTapColorSelectButton`과 같은 식으로 맞추는건 어떠신가요!!?

우선은 기본 형태롤 did+...의 형식으로 맞추는건 좋아보입니다 전 ㅋㅋ

**Comment by Hansolkkim** [comment]
오 말씀 주신거처럼 수정하면 다들 공통점을 가질 수 있을거 같네요ㅎㅎ

**Comment by Hansolkkim** [comment]
|GoalCoordinator|AlbumCoordinator|PhotoEditCoordinator|
|---|---|---|
|![SS2022-10-31PM07 27 55](https://user-images.githubusercontent.com/92504186/198987400-e7667021-e134-49f8-a287-8c1bc046c7d0.jpg)|![SS2022-10-31PM07 28 13](https://user-images.githubusercontent.com/92504186/198987444-c67b85c4-d94c-4d49-b19b-8ac5c37d95a4.jpg)|![SS2022-10-31PM07 28 37](https://user-images.githubusercontent.com/92504186/198987518-8305957e-dba9-43b3-b91f-ec82050afb18.jpg)|

@junu0516 
일단 이렇게 한 번 바꿔봤는데 어떠신가요??

**Comment by junu0516** [comment]
@Hansolkkim 
오..싹다 바꿔주셨네요 ㅋㅋ 감사합니다 
완전 좋아요 ㅋㅋ😁
